[package]
name = "historyprovider"
description = "historyprovider-rs"
license = "MIT"
repository = "https://github.com/silicon-heaven/historyprovider-rs"
version = "3.3.1"
edition = "2024"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

[[bin]]
name = "hp"

[dependencies]
tokio = { version = "1.52.3", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"], default-features = false }
shvproto = "8.0.0"
shvrpc = { version = "21.0", features = ["journal"] }
shvclient = { version = "11.0", features = ["tokio"] }
futures = "0.3.32"
log = "0.4.33"
clap = { version = "4.6.1", features = ["derive"] }
# simple_logger = { version = "5.0.0", features = ["stderr"] }
simple_logger = { version = "5.2.0" }
url = "2.5.8"
duration-str = "0.21"
sha1 = "0.11.0"
hex = "0.4.3"
tokio-util = { version = "0.7.18", features = ["io"] }
async-compression = { version = "0.4.42", features = ["gzip", "tokio"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio-stream = { version = "0.1.18", features = ["fs"] }
time = { version = "0.3.51", features = ["formatting"] }
chrono = "0.4.45"
humantime = "2.3.0"
size = { version = "0.5.0", features = ["serde"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite"] }

# [patch.crates-io]
# shvrpc = { path = "../libshvrpc-rs" }
# shvproto = { path = "../libshvproto-rs" }
# shvclient = { path = "../libshvclient-rs" }


[dev-dependencies]
async-broadcast = "0.7.2"
async-trait = "0.1.92"
shvclient = { version = "11.0", features = ["mocking", "tokio"] }
tempfile = "3.27.0"

[lints.clippy]
pedantic = {priority = -1, level = "warn"}

allow_attributes = "warn"
allow_attributes_without_reason = "warn"
box_collection = "warn"
dbg_macro = "warn"
enum_variant_names = "warn"
equatable_if_let = "warn"
exit = "warn"
indexing_slicing = "warn"
infinite_loop = "warn"
iter_on_single_items = "warn"
large_types_passed_by_value = "warn"
let_underscore_must_use = "warn"
linkedlist = "warn"
map_err_ignore = "warn"
needless_pass_by_ref_mut = "warn"
option_if_let_else = "warn"
option_option = "warn"
or_fun_call = "warn"
owned_cow = "warn"
print_stderr = "warn"
print_stdout = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_allocation = "warn"
redundant_clone = "warn"
redundant_type_annotations = "warn"
ref_option = "warn"
rest_pat_in_fully_bound_structs = "warn"
return_and_then = "warn"
string_lit_as_bytes = "warn"
string_slice = "warn"
trivially_copy_pass_by_ref = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unnecessary_box_returns = "warn"
unnecessary_wraps = "warn"
unneeded_field_pattern = "warn"
unused_self = "warn"
unwrap_used = "warn"
upper_case_acronyms = "warn"
useless_let_if_seq = "warn"
vec_box = "warn"
wrong_self_convention = "warn"

case_sensitive_file_extension_comparisons = "allow"
doc_markdown = "allow"
expect_used = "allow"
explicit_iter_loop = "allow"
float_cmp = "allow"
format_push_string = "allow"
if_not_else = "allow"
items_after_statements = "allow"
inconsistent_struct_constructor = "allow"
large_futures = "allow"
manual_string_new = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
should_panic_without_expect = "allow"
struct_excessive_bools = "allow"
struct_field_names = "allow"
todo = "allow"
too_many_lines = "allow"
