name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

permissions:
  # For syyyr/rust-pycobertura-action
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu
        include:
          - target: aarch64-unknown-linux-gnu
            filename_suffix: arm64
            features: --all-features
          - target: armv7-unknown-linux-gnueabihf
            filename_suffix: armv7
            features: --no-default-features
          - target: x86_64-unknown-linux-gnu
            filename_suffix: amd64
            features: --all-features

    steps:
      - uses: actions/checkout@v7
      - name: Configure cross environment
        uses: zijiren233/cargo-cross@v1
        with:
          command: setup
          cross-args: --target ${{matrix.target}}

      - name: Clippy
        run: cargo cross clippy --release --all-targets ${{matrix.features}} --target ${{matrix.target}}
      - name: Build
        run: cargo cross build --release ${{matrix.features}} --target ${{matrix.target}}
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo cross test --release --all-features --target ${{matrix.target}}

      - name: Get version from Cargo.toml
        id: get-version
        run: |
          version="$(grep '^version' Cargo.toml | head -n1 | sed 's/version\s*=\s*"\(.*\)"/\1/')"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Rename artifacts
        run: |
          mv "target/${{matrix.target}}/release/hp" "target/${{matrix.target}}/release/historyprovider-${{steps.get-version.outputs.version}}-${{matrix.filename_suffix}}"

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{matrix.target}}
          path: target/${{matrix.target}}/release/historyprovider-${{steps.get-version.outputs.version}}-${{matrix.filename_suffix}}

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Generate coverage
        uses: syyyr/rust-pycobertura-action@v4.1.0
        with:
          project_name: historyprovider-rs

  create-releases:
    name: Create releases
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Consolidate artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Get version from Cargo.toml
        id: get-version
        run: |
          version="$(grep '^version' Cargo.toml | head -n1 | sed 's/version\s*=\s*"\(.*\)"/\1/')"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: historyprovider ${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
          fail_on_unmatched_files: true
          make_latest: true
          body: |
            historyprovider ${{ steps.get-version.outputs.version }}

            If you find any bugs, please report them to the repository's issue tracker.
          files: |
            ${{github.workspace}}/historyprovider-${{ steps.get-version.outputs.version }}-*
